# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yq42mZUQDUAJOyzOgDdFAUUVka9Kh1k6
"""

!pip install googlemaps
!pip install serpapi
!pip install pytesseract

import cv2
import pytesseract
from urllib.parse import quote_plus
import webbrowser
import matplotlib.pyplot as plt




def generar_link_maps(lugar: str) -> str:
    """
    Genera un URL de Google Maps para búsqueda del 'lugar' dado.
    Ejemplo de uso:
        generar_link_maps("Museo Nacional de Antropología, Ciudad de México")
    """
    if not lugar:
        raise ValueError("El parámetro 'lugar' no puede estar vacío.")
    query = quote_plus(lugar)  # codifica espacios y caracteres especiales
    url = f"https://www.google.com/maps/search/?api=1&query={query}"
    return url

# Ejemplo rápido
if __name__ == "__main__":
    lugar = "Macchina"
    link = generar_link_maps(lugar)
    print("Link generado:", link)

    Macchina = cv2.imread("Macchina.png")
    Macchina = cv2.cvtColor(Macchina,cv2.COLOR_BGR2RGB)

    Macchina_negative = cv2.bitwise_not(Macchina)
    Macchina_negative = cv2.cvtColor(Macchina_negative, cv2.COLOR_BGR2GRAY)
    Macchina_negative = cv2.erode(Macchina_negative, None, iterations=3)

    plt.figure()
    plt.imshow(Macchina_negative,cmap ="gray")
    plt.title("Macchina Negativa")
    plt.axis("off")


    strings = pytesseract.image_to_string(Macchina_negative)
    print("Resultado = " + strings)


    The_Coffee = cv2.imread("The Coffee.png")
    The_Coffee = cv2.cvtColor(The_Coffee,cv2.COLOR_BGR2RGB)

    The_Coffee = cv2.bitwise_not(The_Coffee)
    The_Coffee = cv2.cvtColor(The_Coffee, cv2.COLOR_BGR2GRAY)
    The_Coffee = cv2.dilate(The_Coffee, None, iterations=1)

    plt.figure()
    plt.imshow(The_Coffee,cmap ="gray")
    plt.title("The Coffee Aleden Puerta negative")
    plt.axis("off")


    strings = pytesseract.image_to_string(The_Coffee)
    print("Resultado = " + strings)


    # Opcional: abrir automáticamente en el navegador
    abrir = False  # cambiar a True si quieres que se abra
    if abrir:
        webbrowser.open(link)

def generar_link_maps(lugar: str) -> str:
    """
    Genera un URL de Google Maps para búsqueda del 'lugar' dado.
    Ejemplo de uso:
        generar_link_maps("Museo Nacional de Antropología, Ciudad de México")
    """
    if not lugar:
        raise ValueError("El parámetro 'lugar' no puede estar vacío.")
    query = quote_plus(lugar)  # codifica espacios y caracteres especiales
    url = f"https://www.google.com/maps/search/?api=1&query={query}"
    return url

# Ejemplo rápido
if __name__ == "__main__":
    lugar = "The Coffee Aleden Puerta"
    link = generar_link_maps(lugar)
    print("Link generado:", link)

    # Opcional: abrir automáticamente en el navegador
    abrir = False  # cambiar a True si quieres que se abra
    if abrir:
        webbrowser.open(link)

    ##Usar pytesseract